apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: psc32vxp9-python
  janus-idp.io/tekton: psc32vxp9-python
  backstage.io/kubernetes-id: psc32vxp9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: psc32vxp9-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
